--
-- When developing a new model, it's good to assume nothing
-- exists from before. Later we'll amend this.
--

DROP TABLE IF EXISTs scan_type;
DROP TABLE IF EXISTS scanner_type;
DROP TABLE IF EXISTS scanner;
DROP TABLE IF EXISTS scan;
DROP TABLE IF EXISTS ble_report;
DROP TABLE IF EXISTS iBeaconReport;
DROP TABLE IF EXISTS uuid_16_bit;

--
-- Table definitions
--

CREATE TABLE IF NOT EXISTS scan_type
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  description TEXT
);
INSERT INTO scan_type(name, description)
VALUES ('bt', 'Bluetooth');

CREATE TABLE  IF NOT EXISTS scanner_type
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL
);

INSERT INTO scanner_type(name, description)
VALUES ('ESP-32CAM', 'ESP-32CAM based bluetooth/ethernet scanner');

CREATE TABLE  IF NOT EXISTS scanner
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scannerTypeId INTEGER,
    mac TEXT NOT NULL UNIQUE,
    FOREIGN KEY(scannerTypeId) REFERENCES scanner_type(id)
);

INSERT INTO scanner(mac, scannerType)
VALUES ("7C:9E:BD:4B:2F:1C", 1);

CREATE TABLE IF NOT EXISTS  scan
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scannerId  INTEGER NOT NULL,
    timeOfScan INTEGER NOT NULL,
    scanTypeId   INTEGER NOT NULL,
    ipAddress  TEXT NOT NULL,
    FOREIGN KEY(scannerId) REFERENCES scanner(id),
    FOREIGN KEY(scanType) REFERENCES  scan_type(id)
);

INSERT INTO scan(scannerId, timeofScan, scanType, ipAddress)
VALUES (1, 1, 1, "10.0.0.35");

CREATE TABLE IF NOT EXISTS  ble_report
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scanId INTEGER  NOT NULL,
    bleAddress  TEXT NOT NULL,
    name TEXT,
    rssi INTEGER NOT NULL,
    haveTxPowr  INTEGER,
    serviceUUID   TEXT,
    uuid16Bit  TEXT,
    FOREIGN KEY(scanId) REFERENCES scan(id)
);

INSERT INTO ble_report(scanId, bleAddress, rssi, serviceUUID, uuid16Bit)
VALUES (1, "0b:b0:d5:e9:5d:04", -37, "0000fd6f-0000-1000-8000-00805f9b34fb", "fd6f");

CREATE TABLE IF NOT EXISTS iBeaconReport
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ble_report_id INTEGER NOT NULL,
    manufacturerId INTEGER NOT NULL,
    major INTEGER NOT NULL,
    minor INTEGER NOT NULL,
    proximityUUID TEXT NOT NULL,
    power INTEGER,
    FOREIGN KEY(ble_report_id) REFERENCES ble_report(id)
);

INSERT INTO iBeaconReport(ble_report_id, manufacturerId, major, minor, proximityUUID, power)
VALUES (1, 76, 2840, 8568,  "051075e0-2737-ab65-e885-5b84a2195b00", 90);






--
-- Manufacturer data
--

--- TODO: Names are placeholders, look them up to figure out what they really are

CREATE TABLE IF NOT EXISTS uuid_16_bit (
       id INTEGER PRIMARY KEY AUTOINCREMENT,
       uuid16Bit TEXT NOT NULL,
       serviceName TEXT NOT NULL,
       serviceType TEXT NOT NULL
);

INSERT INTO uuid_16_bit (uuid16bit, serviceName, serviceType)
VALUES
  ("2adc", "Mesh Provisioning Data Out", "GATT Characteristic and Object Type") ,
  ("2add", "Mesh Proxy Data In", "GATT Characteristic and Object Type"),
  ("2ade", "Mesh Proxy Data Out", "GATT Characteristic and Object Type"),
  ("2ae0", "Average Current", "GATT Characteristic and Object Type"),
  ("2ae1", "Average Voltage", "GATT Characteristic and Object Type"),
  ("2ae2", "Boolean", "GATT Characteristic and Object Type"),
  ("2ae3", "Chromatic Distance From Planckian", "GATT Characteristic and Object Type"),
  ("2ae4", "Chromaticity Coordinates", "GATT Characteristic and Object Type"),
  ("2ae5", "Chromaticity in CCT And Duv Values", "GATT Characteristic and Object Type"),
  ("2ae6", "Chromaticity Tolerance", "GATT Characteristic and Object Type"),
  ("2ae7", "CIE 13.3-1995 Color Rendering Index", "GATT Characteristic and Object Type"),
  ("2ae8", "Coefficient", "GATT Characteristic and Object Type"),
  ("2ae9", "Correlated Color Temperature", "GATT Characteristic and Object Type"),
  ("2aea", "Count 16", "GATT Characteristic and Object Type"),
  ("2aeb", "Count 24", "GATT Characteristic and Object Type"),
  ("2aec", "Country Code", "GATT Characteristic and Object Type"),
  ("2aed", "Date UTC", "GATT Characteristic and Object Type"),
  ("2aee", "Electric Current", "GATT Characteristic and Object Type"),
  ("2aef", "Electric Current Range", "GATT Characteristic and Object Type"),
  ("2af0", "Electric Current Specification", "GATT Characteristic and Object Type"),
  ("2af1", "Electric Current Statistics", "GATT Characteristic and Object Type"),
  ("2af2", "Energy", "GATT Characteristic and Object Type"),
  ("2af3", "Energy In A Period Of Day", "GATT Characteristic and Object Type"),
  ("2af4", "Event Statistics", "GATT Characteristic and Object Type"),
  ("2af5", "Fixed String 16", "GATT Characteristic and Object Type"),
  ("2af6", "Fixed String 24", "GATT Characteristic and Object Type"),
  ("2af7", "Fixed String 36", "GATT Characteristic and Object Type"),
  ("2af8", "Fixed String 8", "GATT Characteristic and Object Type"),
  ("2af9", "Generic Level", "GATT Characteristic and Object Type"),
  ("2afa", "Global Trade Item Number", "GATT Characteristic and Object Type"),
  ("2afb", "Illuminance", "GATT Characteristic and Object Type"),
  ("2afc", "Luminous Efficacy", "GATT Characteristic and Object Type"),
  ("2afd", "Luminous Energy", "GATT Characteristic and Object Type"),
  ("2afe", "Luminous Exposure", "GATT Characteristic and Object Type"),
  ("2aff", "Luminous Flux", "GATT Characteristic and Object Type"),
  ("0001", "SDP", "Protocol Identifier"),
  ("0002", "UDP", "Protocol Identifier"),
  ("0003", "RFCOMM", "Protocol Identifier"),
  ("0004", "TCP", "Protocol Identifier"),
  ("0005", "TCS-BIN", "Protocol Identifier"),
  ("0006", "TCS-AT", "Protocol Identifier"),
  ("0007", "ATT", "Protocol Identifier"),
  ("0008", "OBEX", "Protocol Identifier"),
  ("0009", "IP", "Protocol Identifier"),
  ("000a", "FTP", "Protocol Identifier"),
  ("000c", "HTTP", "Protocol Identifier"),
  ("000e", "WSP", "Protocol Identifier"),
  ("000f", "BNEP", "Protocol Identifier"),
  ("0010", "UPNP", "Protocol Identifier"),
  ("0011", "HIDP", "Protocol Identifier"),
  ("0012", "HardcopyControlChannel", "Protocol Identifier"),
  ("0014", "HardcopyDataChannel", "Protocol Identifier"),
  ("0016", "HardcopyNotification", "Protocol Identifier"),
  ("0017", "AVCTP", "Protocol Identifier"),
  ("0019", "AVDTP", "Protocol Identifier"),
  ("001b", "CMTP", "Protocol Identifier"),
  ("001e", "MCAPControlChannel", "Protocol Identifier"),
  ("001f", "MCAPDataChannel", "Protocol Identifier"),
  ("0100", "L2CAP", "Protocol Identifier"),
  ("1000", "ServiceDiscoveryServerServiceClassID", "Service Classes and Profiles"),
  ("1001", "BrowseGroupDescriptorServiceClassID", "Service Classes and Profiles"),
  ("1101", "SerialPort", "Service Classes and Profiles"),
  ("1102", "LANAccessUsingPPP", "Service Classes and Profiles"),
  ("1103", "DialupNetworking", "Service Classes and Profiles"),
  ("1104", "IrMCSync", "Service Classes and Profiles"),
  ("1105", "OBEXObjectPush", "Service Classes and Profiles"),
  ("1106", "OBEXFileTransfer", "Service Classes and Profiles"),
  ("1107", "IrMCSyncCommand", "Service Classes and Profiles"),
  ("1108", "Headset", "Service Classes and Profiles"),
  ("1109", "CordlessTelephony", "Service Classes and Profiles"),
  ("110a", "AudioSource", "Service Classes and Profiles"),
  ("110b", "AudioSink", "Service Classes and Profiles"),
  ("110c", "A/V_RemoteControlTarget", "Service Classes and Profiles"),
  ("110d", "AdvancedAudioDistribution", "Service Classes and Profiles"),
  ("110e", "A/V_RemoteControl", "Service Classes and Profiles"),
  ("110f", "A/V_RemoteControlController", "Service Classes and Profiles"),
  ("1110", "Intercom", "Service Classes and Profiles"),
  ("1111", "Fax", "Service Classes and Profiles"),
  ("1112", "Headset - Audio Gateway", "Service Classes and Profiles"),
  ("1113", "WAP", "Service Classes and Profiles"),
  ("1114", "WAP_CLIENT", "Service Classes and Profiles"),
  ("1115", "PANU", "Service Classes and Profiles"),
  ("1116", "NAP", "Service Classes and Profiles"),
  ("1117", "GN", "Service Classes and Profiles"),
  ("1118", "DirectPrinting", "Service Classes and Profiles"),
  ("1119", "ReferencePrinting", "Service Classes and Profiles"),
  ("111a", "Basic Imaging Profile", "Service Classes and Profiles"),
  ("111b", "ImagingResponder", "Service Classes and Profiles"),
  ("111c", "ImagingAutomaticArchive", "Service Classes and Profiles"),
  ("111d", "ImagingReferencedObjects", "Service Classes and Profiles"),
  ("111e", "Handsfree", "Service Classes and Profiles"),
  ("111f", "HandsfreeAudioGateway", "Service Classes and Profiles"),
  ("1120", "DirectPrintingReferenceObjectsService", "Service Classes and Profiles"),
  ("1121", "ReflectedUI", "Service Classes and Profiles"),
  ("1122", "BasicPrinting", "Service Classes and Profiles"),
  ("1123", "PrintingStatus", "Service Classes and Profiles"),
  ("1124", "HumanInterfaceDeviceService", "Service Classes and Profiles"),
  ("1125", "HardcopyCableReplacement", "Service Classes and Profiles"),
  ("1126", "HCR_Print", "Service Classes and Profiles"),
  ("1127", "HCR_Scan", "Service Classes and Profiles"),
  ("1128", "Common_ISDN_Access", "Service Classes and Profiles"),
  ("112d", "SIM_Access", "Service Classes and Profiles"),
  ("112e", "Phonebook Access - PCE", "Service Classes and Profiles"),
  ("112f", "Phonebook Access - PSE", "Service Classes and Profiles"),
  ("1130", "Phonebook Access", "Service Classes and Profiles"),
  ("1131", "Headset - HS", "Service Classes and Profiles"),
  ("1132", "Message Access Server", "Service Classes and Profiles"),
  ("1133", "Message Notification Server", "Service Classes and Profiles"),
  ("1134", "Message Access Profile", "Service Classes and Profiles"),
  ("1135", "GNSS", "Service Classes and Profiles"),
  ("1136", "GNSS_Server", "Service Classes and Profiles"),
  ("1137", "3D Display", "Service Classes and Profiles"),
  ("1138", "3D Glasses", "Service Classes and Profiles"),
  ("1139", "3D Synchronization", "Service Classes and Profiles"),
  ("113a", "MPS Profile UUID", "Service Classes and Profiles"),
  ("113b", "MPS SC UUID", "Service Classes and Profiles"),
  ("113c", "CTN Access Service", "Service Classes and Profiles"),
  ("113d", "CTN Notification Service", "Service Classes and Profiles"),
  ("113e", "CTN Profile", "Service Classes and Profiles"),
  ("1200", "PnPInformation", "Service Classes and Profiles"),
  ("1201", "GenericNetworking", "Service Classes and Profiles"),
  ("1202", "GenericFileTransfer", "Service Classes and Profiles"),
  ("1203", "GenericAudio", "Service Classes and Profiles"),
  ("1204", "GenericTelephony", "Service Classes and Profiles"),
  ("1205", "UPNP_Service", "Service Classes and Profiles"),
  ("1206", "UPNP_IP_Service", "Service Classes and Profiles"),
  ("1300", "ESDP_UPNP_IP_PAN", "Service Classes and Profiles"),
  ("1301", "ESDP_UPNP_IP_LAP", "Service Classes and Profiles"),
  ("1302", "ESDP_UPNP_L2CAP", "Service Classes and Profiles"),
  ("1303", "VideoSource", "Service Classes and Profiles"),
  ("1304", "VideoSink", "Service Classes and Profiles"),
  ("1305", "VideoDistribution", "Service Classes and Profiles"),
  ("1400", "HDP", "Service Classes and Profiles"),
  ("1401", "HDP Source", "Service Classes and Profiles"),
  ("1402", "HDP Sink", "Service Classes and Profiles"),
  ("1800", "Generic Access", "GATT Service"),
  ("1801", "Generic Attribute", "GATT Service"),
  ("1802", "Immediate Alert", "GATT Service"),
  ("1803", "Link Loss", "GATT Service"),
  ("1804", "Tx Power", "GATT Service"),
  ("1805", "Current Time", "GATT Service"),
  ("1806", "Reference Time Update", "GATT Service"),
  ("1807", "Next DST Change", "GATT Service"),
  ("1808", "Glucose", "GATT Service"),
  ("1809", "Health Thermometer", "GATT Service"),
  ("180a", "Device Information", "GATT Service"),
  ("180d", "Heart Rate", "GATT Service"),
  ("180e", "Phone Alert Status", "GATT Service"),
  ("180f", "Battery", "GATT Service"),
  ("1810", "Blood Pressure", "GATT Service"),
  ("1811", "Alert Notification", "GATT Service"),
  ("1812", "Human Interface Device", "GATT Service"),
  ("1813", "Scan Parameters", "GATT Service"),
  ("1814", "Running Speed and Cadence", "GATT Service"),
  ("1815", "Automation IO", "GATT Service"),
  ("1816", "Cycling Speed and Cadence", "GATT Service"),
  ("1818", "Cycling Power", "GATT Service"),
  ("1819", "Location and Navigation", "GATT Service"),
  ("181a", "Environmental Sensing", "GATT Service"),
  ("181b", "Body Composition", "GATT Service"),
  ("181c", "User Data", "GATT Service"),
  ("181d", "Weight Scale", "GATT Service"),
  ("181e", "Bond Management", "GATT Service"),
  ("181f", "Continuous Glucose Monitoring", "GATT Service"),
  ("1820", "Internet Protocol Support", "GATT Service"),
  ("1821", "Indoor Positioning", "GATT Service"),
  ("1822", "Pulse Oximeter", "GATT Service"),
  ("1823", "HTTP Proxy", "GATT Service"),
  ("1824", "Transport Discovery", "GATT Service"),
  ("1825", "Object Transfer", "GATT Service"),
  ("1826", "Fitness Machine", "GATT Service"),
  ("1827", "Mesh Provisioning", "GATT Service"),
  ("1828", "Mesh Proxy", "GATT Service"),
  ("1829", "Reconnection Configuration", "GATT Service"),
  ("183a", "Insulin Delivery", "GATT Service"),
  ("183b", "Binary Sensor", "GATT Service"),
  ("183c", "Emergency Configuration", "GATT Service"),
  ("183e", "Physical Activity Monitor", "GATT Service"),
  ("1843", "Audio Input Control", "GATT Service"),
  ("1844", "Volume Control", "GATT Service"),
  ("1845", "Volume Offset Control", "GATT Service"),
  ("1846", "Coordinated Set Identification Service", "GATT Service"),
  ("1847", "Device Time", "GATT Service"),
  ("1848", "Media Control Service", "GATT Service"),
  ("1849", "Generic Media Control Service", "GATT Service"),
  ("184a", "Constant Tone Extension", "GATT Service"),
  ("184b", "Telephone Bearer Service", "GATT Service"),
  ("184c", "Generic Telephone Bearer Service", "GATT Service"),
  ("184d", "Microphone Control", "GATT Service"),
  ("2700", "unitless", "GATT Unit"),
  ("2701", "length (metre)", "GATT Unit"),
  ("2702", "mass (kilogram)", "GATT Unit"),
  ("2703", "time (second)", "GATT Unit"),
  ("2704", "electric current (ampere)", "GATT Unit"),
  ("2705", "thermodynamic temperature (kelvin)", "GATT Unit"),
  ("2706", "amount of substance (mole)", "GATT Unit"),
  ("2707", "luminous intensity (candela)", "GATT Unit"),
  ("2710", "area (square metres)", "GATT Unit"),
  ("2711", "volume (cubic metres)", "GATT Unit"),
  ("2712", "velocity (metres per second)", "GATT Unit"),
  ("2713", "acceleration (metres per second squared)", "GATT Unit"),
  ("2714", "wavenumber (reciprocal metre)", "GATT Unit"),
  ("2715", "density (kilogram per cubic metre)", "GATT Unit"),
  ("2716", "surface density (kilogram per square metre)", "GATT Unit"),
  ("2717", "specific volume (cubic metre per kilogram)", "GATT Unit"),
  ("2718", "current density (ampere per square metre)", "GATT Unit"),
  ("2719", "magnetic field strength (ampere per metre)", "GATT Unit"),
  ("271a", "amount concentration (mole per cubic metre)", "GATT Unit"),
  ("271b", "mass concentration (kilogram per cubic metre)", "GATT Unit"),
  ("271c", "luminance (candela per square metre)", "GATT Unit"),
  ("271d", "refractive index", "GATT Unit"),
  ("271e", "relative permeability", "GATT Unit"),
  ("2720", "plane angle (radian)", "GATT Unit"),
  ("2721", "solid angle (steradian)", "GATT Unit"),
  ("2722", "frequency (hertz)", "GATT Unit"),
  ("2723", "force (newton)", "GATT Unit"),
  ("2724", "pressure (pascal)", "GATT Unit"),
  ("2725", "energy (joule)", "GATT Unit"),
  ("2726", "power (watt)", "GATT Unit"),
  ("2727", "electric charge (coulomb)", "GATT Unit"),
  ("2728", "electric potential difference (volt)", "GATT Unit"),
  ("2729", "capacitance (farad)", "GATT Unit"),
  ("272a", "electric resistance (ohm)", "GATT Unit"),
  ("272b", "electric conductance (siemens)", "GATT Unit"),
  ("272c", "magnetic flux (weber)", "GATT Unit"),
  ("272d", "magnetic flux density (tesla)", "GATT Unit"),
  ("272e", "inductance (henry)", "GATT Unit"),
  ("272f", "Celsius temperature (degree Celsius)", "GATT Unit"),
  ("2730", "luminous flux (lumen)", "GATT Unit"),
  ("2731", "illuminance (lux)", "GATT Unit"),
  ("2732", "activity referred to a radionuclide (becquerel)", "GATT Unit"),
  ("2733", "absorbed dose (gray)", "GATT Unit"),
  ("2734", "dose equivalent (sievert)", "GATT Unit"),
  ("2735", "catalytic activity (katal)", "GATT Unit"),
  ("2740", "dynamic viscosity (pascal second)", "GATT Unit"),
  ("2741", "moment of force (newton metre)", "GATT Unit"),
  ("2742", "surface tension (newton per metre)", "GATT Unit"),
  ("2743", "angular velocity (radian per second)", "GATT Unit"),
  ("2744", "angular acceleration (radian per second squared)", "GATT Unit"),
  ("2745", "heat flux density (watt per square metre)", "GATT Unit"),
  ("2746", "heat capacity (joule per kelvin)", "GATT Unit"),
  ("2747", "specific heat capacity (joule per kilogram kelvin)", "GATT Unit"),
  ("2748", "specific energy (joule per kilogram)", "GATT Unit"),
  ("2749", "thermal conductivity (watt per metre kelvin)", "GATT Unit"),
  ("274a", "energy density (joule per cubic metre)", "GATT Unit"),
  ("274b", "electric field strength (volt per metre)", "GATT Unit"),
  ("274c", "electric charge density (coulomb per cubic metre)", "GATT Unit"),
  ("274d", "surface charge density (coulomb per square metre)", "GATT Unit"),
  ("274e", "electric flux density (coulomb per square metre)", "GATT Unit"),
  ("274f", "permittivity (farad per metre)", "GATT Unit"),
  ("2750", "permeability (henry per metre)", "GATT Unit"),
  ("2751", "molar energy (joule per mole)", "GATT Unit"),
  ("2752", "molar entropy (joule per mole kelvin)", "GATT Unit"),
  ("2753", "exposure (coulomb per kilogram)", "GATT Unit"),
  ("2754", "absorbed dose rate (gray per second)", "GATT Unit"),
  ("2755", "radiant intensity (watt per steradian)", "GATT Unit"),
  ("2756", "radiance (watt per square metre steradian)", "GATT Unit"),
  ("2757", "catalytic activity concentration (katal per cubic metre)", "GATT Unit"),
  ("2760", "time (minute)", "GATT Unit"),
  ("2761", "time (hour)", "GATT Unit"),
  ("2762", "time (day)", "GATT Unit"),
  ("2763", "plane angle (degree)", "GATT Unit"),
  ("2764", "plane angle (minute)", "GATT Unit"),
  ("2765", "plane angle (second)", "GATT Unit"),
  ("2766", "area (hectare)", "GATT Unit"),
  ("2767", "volume (litre)", "GATT Unit"),
  ("2768", "mass (tonne)", "GATT Unit"),
  ("2780", "pressure (bar)", "GATT Unit"),
  ("2781", "pressure (millimetre of mercury)", "GATT Unit"),
  ("2782", "length ( ngstr m)", "GATT Unit"),
  ("2783", "length (nautical mile)", "GATT Unit"),
  ("2784", "area (barn)", "GATT Unit"),
  ("2785", "velocity (knot)", "GATT Unit"),
  ("2786", "logarithmic radio quantity (neper)", "GATT Unit"),
  ("2787", "logarithmic radio quantity (bel)", "GATT Unit"),
  ("27a0", "length (yard)", "GATT Unit"),
  ("27a1", "length (parsec)", "GATT Unit"),
  ("27a2", "length (inch)", "GATT Unit"),
  ("27a3", "length (foot)", "GATT Unit"),
  ("27a4", "length (mile)", "GATT Unit"),
  ("27a5", "pressure (pound-force per square inch)", "GATT Unit"),
  ("27a6", "velocity (kilometre per hour)", "GATT Unit"),
  ("27a7", "velocity (mile per hour)", "GATT Unit"),
  ("27a8", "angular velocity (revolution per minute)", "GATT Unit"),
  ("27a9", "energy (gram calorie)", "GATT Unit"),
  ("27aa", "energy (kilogram calorie)", "GATT Unit"),
  ("27ab", "energy (kilowatt hour)", "GATT Unit"),
  ("27ac", "thermodynamic temperature (degree Fahrenheit)", "GATT Unit"),
  ("27ad", "percentage", "GATT Unit"),
  ("27ae", "per mille", "GATT Unit"),
  ("27af", "period (beats per minute)", "GATT Unit"),
  ("27b0", "electric charge (ampere hours)", "GATT Unit"),
  ("27b1", "mass density (milligram per decilitre)", "GATT Unit"),
  ("27b2", "mass density (millimole per litre)", "GATT Unit"),
  ("27b3", "time (year)", "GATT Unit"),
  ("27b4", "time (month)", "GATT Unit"),
  ("27b5", "concentration (count per cubic metre)", "GATT Unit"),
  ("27b6", "irradiance (watt per square metre)", "GATT Unit"),
  ("27b7", "milliliter (per kilogram per minute)", "GATT Unit"),
  ("27b8", "mass (pound)", "GATT Unit"),
  ("27b9", "metabolic equivalent", "GATT Unit"),
  ("27ba", "step (per minute)", "GATT Unit"),
  ("27bc", "stroke (per minute)", "GATT Unit"),
  ("27bd", "pace (kilometre per minute)", "GATT Unit"),
  ("27be", "luminous efficacy (lumen per watt)", "GATT Unit"),
  ("27bf", "luminous energy (lumen hour)", "GATT Unit"),
  ("27c0", "luminous exposure (lux hour)", "GATT Unit"),
  ("27c1", "mass flow (gram per second)", "GATT Unit"),
  ("27c2", "volume flow (litre per second)", "GATT Unit"),
  ("27c3", "sound pressure (decible)", "GATT Unit"),
  ("27c4", "parts per million", "GATT Unit"),
  ("27c5", "parts per billion", "GATT Unit"),
  ("2800", "Primary Service", "GATT Declarations"),
  ("2801", "Secondary Service", "GATT Declarations"),
  ("2802", "Include", "GATT Declarations"),
  ("2803", "Characteristic", "GATT Declarations"),
  ("2900", "Characteristic Extended Properties", "GATT Descriptor"),
  ("2901", "Characteristic User Description", "GATT Descriptor"),
  ("2902", "Client Characteristic Configuration", "GATT Descriptor"),
  ("2903", "Server Characteristic Configuration", "GATT Descriptor"),
  ("2904", "Characteristic Presentation Format", "GATT Descriptor"),
  ("2905", "Characteristic Aggregate Format", "GATT Descriptor"),
  ("2906", "Valid Range", "GATT Descriptor"),
  ("2907", "External Report Reference", "GATT Descriptor"),
  ("2908", "Report Reference", "GATT Descriptor"),
  ("2909", "Number of Digitals", "GATT Descriptor"),
  ("290a", "Value Trigger Setting", "GATT Descriptor"),
  ("290b", "Environmental Sensing Configuration", "GATT Descriptor"),
  ("290c", "Environmental Sensing Measurement", "GATT Descriptor"),
  ("290d", "Environmental Sensing Trigger Setting", "GATT Descriptor"),
  ("290e", "Time Trigger Setting", "GATT Descriptor"),
  ("290f", "Complete BR-EDR Transport Block Data", "GATT Descriptor"),
  ("2a00", "Device Name", "GATT Characteristic and Object Type"),
  ("2a01", "Appearance", "GATT Characteristic and Object Type"),
  ("2a02", "Peripheral Privacy Flag", "GATT Characteristic and Object Type"),
  ("2a03", "Reconnection Address", "GATT Characteristic and Object Type"),
  ("2a04", "Peripheral Preferred Connection Parameters", "GATT Characteristic and Object Type"),
  ("2a05", "Service Changed", "GATT Characteristic and Object Type"),
  ("2a06", "Alert Level", "GATT Characteristic and Object Type"),
  ("2a07", "Tx Power Level", "GATT Characteristic and Object Type"),
  ("2a08", "Date Time", "GATT Characteristic and Object Type"),
  ("2a09", "Day of Week", "GATT Characteristic and Object Type"),
  ("2a0a", "Day Date Time", "GATT Characteristic and Object Type"),
  ("2a0c", "Exact Time 256", "GATT Characteristic and Object Type"),
  ("2a0d", "DST Offset", "GATT Characteristic and Object Type"),
  ("2a0e", "Time Zone", "GATT Characteristic and Object Type"),
  ("2a0f", "Local Time Information", "GATT Characteristic and Object Type"),
  ("2a11", "Time with DST", "GATT Characteristic and Object Type"),
  ("2a12", "Time Accuracy", "GATT Characteristic and Object Type"),
  ("2a13", "Time Source", "GATT Characteristic and Object Type"),
  ("2a14", "Reference Time Information", "GATT Characteristic and Object Type"),
  ("2a16", "Time Update Control Point", "GATT Characteristic and Object Type"),
  ("2a17", "Time Update State", "GATT Characteristic and Object Type"),
  ("2a18", "Glucose Measurement", "GATT Characteristic and Object Type"),
  ("2a19", "Battery Level", "GATT Characteristic and Object Type"),
  ("2a1c", "Temperature Measurement", "GATT Characteristic and Object Type"),
  ("2a1d", "Temperature Type", "GATT Characteristic and Object Type"),
  ("2a1e", "Intermediate Temperature", "GATT Characteristic and Object Type"),
  ("2a21", "Measurement Interval", "GATT Characteristic and Object Type"),
  ("2a22", "Boot Keyboard Input Report", "GATT Characteristic and Object Type"),
  ("2a23", "System ID", "GATT Characteristic and Object Type"),
  ("2a24", "Model Number String", "GATT Characteristic and Object Type"),
  ("2a25", "Serial Number String", "GATT Characteristic and Object Type"),
  ("2a26", "Firmware Revision String", "GATT Characteristic and Object Type"),
  ("2a27", "Hardware Revision String", "GATT Characteristic and Object Type"),
  ("2a28", "Software Revision String", "GATT Characteristic and Object Type"),
  ("2a29", "Manufacturer Name String", "GATT Characteristic and Object Type"),
  ("2a2a", "IEEE 11073-20601 Regulatory Certification Data List", "GATT Characteristic and Object Type"),
  ("2a2b", "Current Time", "GATT Characteristic and Object Type"),
  ("2a31", "Scan Refresh", "GATT Characteristic and Object Type"),
  ("2a32", "Boot Keyboard Output Report", "GATT Characteristic and Object Type"),
  ("2a33", "Boot Mouse Input Report", "GATT Characteristic and Object Type"),
  ("2a34", "Glucose Measurement Context", "GATT Characteristic and Object Type"),
  ("2a35", "Blood Pressure Measurement", "GATT Characteristic and Object Type"),
  ("2a36", "Intermediate Cuff Pressure", "GATT Characteristic and Object Type"),
  ("2a37", "Heart Rate Measurement", "GATT Characteristic and Object Type"),
  ("2a38", "Body Sensor Location", "GATT Characteristic and Object Type"),
  ("2a39", "Heart Rate Control Point", "GATT Characteristic and Object Type"),
  ("2a3f", "Alert Status", "GATT Characteristic and Object Type"),
  ("2a40", "Ringer Control Point", "GATT Characteristic and Object Type"),
  ("2a41", "Ringer Setting", "GATT Characteristic and Object Type"),
  ("2a42", "Alert Category ID Bit Mask", "GATT Characteristic and Object Type"),
  ("2a43", "Alert Category ID", "GATT Characteristic and Object Type"),
  ("2a44", "Alert Notification Control Point", "GATT Characteristic and Object Type"),
  ("2a45", "Unread Alert Status", "GATT Characteristic and Object Type"),
  ("2a46", "New Alert", "GATT Characteristic and Object Type"),
  ("2a47", "Supported New Alert Category", "GATT Characteristic and Object Type"),
  ("2a48", "Supported Unread Alert Category", "GATT Characteristic and Object Type"),
  ("2a49", "Blood Pressure Feature", "GATT Characteristic and Object Type"),
  ("2a4a", "HID Information", "GATT Characteristic and Object Type"),
  ("2a4b", "Report Map", "GATT Characteristic and Object Type"),
  ("2a4c", "HID Control Point", "GATT Characteristic and Object Type"),
  ("2a4d", "Report", "GATT Characteristic and Object Type"),
  ("2a4e", "Protocol Mode", "GATT Characteristic and Object Type"),
  ("2a4f", "Scan Interval Window", "GATT Characteristic and Object Type"),
  ("2a50", "PnP ID", "GATT Characteristic and Object Type"),
  ("2a51", "Glucose Feature", "GATT Characteristic and Object Type"),
  ("2a52", "Record Access Control Point", "GATT Characteristic and Object Type"),
  ("2a53", "RSC Measurement", "GATT Characteristic and Object Type"),
  ("2a54", "RSC Feature", "GATT Characteristic and Object Type"),
  ("2a55", "SC Control Point", "GATT Characteristic and Object Type"),
  ("2a5a", "Aggregate", "GATT Characteristic and Object Type"),
  ("2a5b", "CSC Measurement", "GATT Characteristic and Object Type"),
  ("2a5c", "CSC Feature", "GATT Characteristic and Object Type"),
  ("2a5d", "Sensor Location", "GATT Characteristic and Object Type"),
  ("2a5e", "PLX Spot-Check Measurement", "GATT Characteristic and Object Type"),
  ("2a5f", "PLX Continuous Measurement", "GATT Characteristic and Object Type"),
  ("2a60", "PLX Features", "GATT Characteristic and Object Type"),
  ("2a63", "Cycling Power Measurement", "GATT Characteristic and Object Type"),
  ("2a64", "Cycling Power Vector", "GATT Characteristic and Object Type"),
  ("2a65", "Cycling Power Feature", "GATT Characteristic and Object Type"),
  ("2a66", "Cycling Power Control Point", "GATT Characteristic and Object Type"),
  ("2a67", "Location and Speed", "GATT Characteristic and Object Type"),
  ("2a68", "Navigation", "GATT Characteristic and Object Type"),
  ("2a69", "Position Quality", "GATT Characteristic and Object Type"),
  ("2a6a", "LN Feature", "GATT Characteristic and Object Type"),
  ("2a6b", "LN Control Point", "GATT Characteristic and Object Type"),
  ("2a6c", "Elevation", "GATT Characteristic and Object Type"),
  ("2a6d", "Pressure", "GATT Characteristic and Object Type"),
  ("2a6e", "Temperature", "GATT Characteristic and Object Type"),
  ("2a6f", "Humidity", "GATT Characteristic and Object Type"),
  ("2a70", "True Wind Speed", "GATT Characteristic and Object Type"),
  ("2a71", "True Wind Direction", "GATT Characteristic and Object Type"),
  ("2a72", "Apparent Wind Speed", "GATT Characteristic and Object Type"),
  ("2a73", "Apparent Wind Direction", "GATT Characteristic and Object Type"),
  ("2a74", "Gust Factor", "GATT Characteristic and Object Type"),
  ("2a75", "Pollen Concentration", "GATT Characteristic and Object Type"),
  ("2a76", "UV Index", "GATT Characteristic and Object Type"),
  ("2a77", "Irradiance", "GATT Characteristic and Object Type"),
  ("2a78", "Rainfall", "GATT Characteristic and Object Type"),
  ("2a79", "Wind Chill", "GATT Characteristic and Object Type"),
  ("2a7a", "Heat Index", "GATT Characteristic and Object Type"),
  ("2a7b", "Dew Point", "GATT Characteristic and Object Type"),
  ("2a7d", "Descriptor Value Changed", "GATT Characteristic and Object Type"),
  ("2a7e", "Aerobic Heart Rate Lower Limit", "GATT Characteristic and Object Type"),
  ("2a7f", "Aerobic Threshold", "GATT Characteristic and Object Type"),
  ("2a80", "Age", "GATT Characteristic and Object Type"),
  ("2a81", "Anaerobic Heart Rate Lower Limit", "GATT Characteristic and Object Type"),
  ("2a82", "Anaerobic Heart Rate Upper Limit", "GATT Characteristic and Object Type"),
  ("2a83", "Anaerobic Threshold", "GATT Characteristic and Object Type"),
  ("2a84", "Aerobic Heart Rate Upper Limit", "GATT Characteristic and Object Type"),
  ("2a85", "Date of Birth", "GATT Characteristic and Object Type"),
  ("2a86", "Date of Threshold Assessment", "GATT Characteristic and Object Type"),
  ("2a87", "Email Address", "GATT Characteristic and Object Type"),
  ("2a88", "Fat Burn Heart Rate Lower Limit", "GATT Characteristic and Object Type"),
  ("2a89", "Fat Burn Heart Rate Upper Limit", "GATT Characteristic and Object Type"),
  ("2a8a", "First Name", "GATT Characteristic and Object Type"),
  ("2a8b", "Five Zone Heart Rate Limits", "GATT Characteristic and Object Type"),
  ("2a8c", "Gender", "GATT Characteristic and Object Type"),
  ("2a8d", "Heart Rate Max", "GATT Characteristic and Object Type"),
  ("2a8e", "Height", "GATT Characteristic and Object Type"),
  ("2a8f", "Hip Circumference", "GATT Characteristic and Object Type"),
  ("2a90", "Last Name", "GATT Characteristic and Object Type"),
  ("2a91", "Maximum Recommended Heart Rate", "GATT Characteristic and Object Type"),
  ("2a92", "Resting Heart Rate", "GATT Characteristic and Object Type"),
  ("2a93", "Sport Type for Aerobic and Anaerobic Thresholds", "GATT Characteristic and Object Type"),
  ("2a94", "Three Zone Heart Rate Limits", "GATT Characteristic and Object Type"),
  ("2a95", "Two Zone Heart Rate Limits", "GATT Characteristic and Object Type"),
  ("2a96", "VO2 Max", "GATT Characteristic and Object Type"),
  ("2a97", "Waist Circumference", "GATT Characteristic and Object Type"),
  ("2a98", "Weight", "GATT Characteristic and Object Type"),
  ("2a99", "Database Change Increment", "GATT Characteristic and Object Type"),
  ("2a9a", "User Index", "GATT Characteristic and Object Type"),
  ("2a9b", "Body Composition Feature", "GATT Characteristic and Object Type"),
  ("2a9c", "Body Composition Measurement", "GATT Characteristic and Object Type"),
  ("2a9d", "Weight Measurement", "GATT Characteristic and Object Type"),
  ("2a9e", "Weight Scale Feature", "GATT Characteristic and Object Type"),
  ("2a9f", "User Control Point", "GATT Characteristic and Object Type"),
  ("2aa0", "Magnetic Flux Density - 2D", "GATT Characteristic and Object Type"),
  ("2aa1", "Magnetic Flux Density - 3D", "GATT Characteristic and Object Type"),
  ("2aa2", "Language", "GATT Characteristic and Object Type"),
  ("2aa3", "Barometric Pressure Trend", "GATT Characteristic and Object Type"),
  ("2aa4", "Bond Management Control Point", "GATT Characteristic and Object Type"),
  ("2aa5", "Bond Management Feature", "GATT Characteristic and Object Type"),
  ("2aa6", "Central Address Resolution", "GATT Characteristic and Object Type"),
  ("2aa7", "CGM Measurement", "GATT Characteristic and Object Type"),
  ("2aa8", "CGM Feature", "GATT Characteristic and Object Type"),
  ("2aa9", "CGM Status", "GATT Characteristic and Object Type"),
  ("2aaa", "CGM Session Start Time", "GATT Characteristic and Object Type"),
  ("2aab", "CGM Session Run Time", "GATT Characteristic and Object Type"),
  ("2aac", "CGM Specific Ops Control Point", "GATT Characteristic and Object Type"),
  ("2aad", "Indoor Positioning Configuration", "GATT Characteristic and Object Type"),
  ("2aae", "Latitude", "GATT Characteristic and Object Type"),
  ("2aaf", "Longitude", "GATT Characteristic and Object Type"),
  ("2ab0", "Local North Coordinate", "GATT Characteristic and Object Type"),
  ("2ab1", "Local East Coordinate", "GATT Characteristic and Object Type"),
  ("2ab2", "Floor Number", "GATT Characteristic and Object Type"),
  ("2ab3", "Altitude", "GATT Characteristic and Object Type"),
  ("2ab4", "Uncertainty", "GATT Characteristic and Object Type"),
  ("2ab5", "Location Name", "GATT Characteristic and Object Type"),
  ("2ab6", "URI", "GATT Characteristic and Object Type"),
  ("2ab7", "HTTP Headers", "GATT Characteristic and Object Type"),
  ("2ab8", "HTTP Status Code", "GATT Characteristic and Object Type"),
  ("2ab9", "HTTP Entity Body", "GATT Characteristic and Object Type"),
  ("2aba", "HTTP Control Point", "GATT Characteristic and Object Type"),
  ("2abb", "HTTPS Security", "GATT Characteristic and Object Type"),
  ("2abc", "TDS Control Point", "GATT Characteristic and Object Type"),
  ("2abd", "OTS Feature", "GATT Characteristic and Object Type"),
  ("2abe", "object name", "GATT Characteristic and Object Type"),
  ("2abf", "object type", "GATT Characteristic and Object Type"),
  ("2ac0", "object size", "GATT Characteristic and Object Type"),
  ("2ac1", "object first created", "GATT Characteristic and Object Type"),
  ("2ac2", "object last modified", "GATT Characteristic and Object Type"),
  ("2ac3", "object ID", "GATT Characteristic and Object Type"),
  ("2ac4", "object properties", "GATT Characteristic and Object Type"),
  ("2ac5", "object actioncontrol point", "GATT Characteristic and Object Type"),
  ("2ac6", "object list control point", "GATT Characteristic and Object Type"),
  ("2ac7", "object list filter", "GATT Characteristic and Object Type"),
  ("2ac8", "object changed", "GATT Characteristic and Object Type"),
  ("2ac9", "Resolvable Private Address Only", "GATT Characteristic and Object Type"),
  ("2aca", "Unspecified", "GATT Characteristic and Object Type"),
  ("2acb", "Directory Listing", "GATT Characteristic and Object Type"),
  ("2acc", "Fitness Machine Feature", "GATT Characteristic and Object Type"),
  ("2acd", "Treadmill Data", "GATT Characteristic and Object Type"),
  ("2ace", "Cross Trainer Data", "GATT Characteristic and Object Type"),
  ("2acf", "Step Climber Data", "GATT Characteristic and Object Type"),
  ("2ad0", "Stair Climber Data", "GATT Characteristic and Object Type"),
  ("2ad1", "Rower Data", "GATT Characteristic and Object Type"),
  ("2ad2", "Indoor Bike Data", "GATT Characteristic and Object Type"),
  ("2ad3", "Training Status", "GATT Characteristic and Object Type"),
  ("2ad4", "Supported Speed Range", "GATT Characteristic and Object Type"),
  ("2ad5", "Supported Inclination Range", "GATT Characteristic and Object Type"),
  ("2ad6", "Supported Resistance Level Range", "GATT Characteristic and Object Type"),
  ("2ad7", "Supported Heart Rate Range", "GATT Characteristic and Object Type"),
  ("2ad8", "Supported Power Range", "GATT Characteristic and Object Type"),
  ("2ad9", "Fitness Machine Control Point", "GATT Characteristic and Object Type"),
  ("2ada", "Fitness Machine Status", "GATT Characteristic and Object Type"),
  ("2adb", "Mesh Provisioning Data In", "GATT Characteristic and Object Type"),
  ("2b00", "Luminous Flux Range", "GATT Characteristic and Object Type"),
  ("2b01", "Luminous Intensity", "GATT Characteristic and Object Type"),
  ("2b02", "Mass Flow", "GATT Characteristic and Object Type"),
  ("2b03", "Perceived Lightness", "GATT Characteristic and Object Type"),
  ("2b04", "Percentage 8", "GATT Characteristic and Object Type"),
  ("2b05", "Power", "GATT Characteristic and Object Type"),
  ("2b06", "Power Specification", "GATT Characteristic and Object Type"),
  ("2b07", "Relative Runtime In A Current Range", "GATT Characteristic and Object Type"),
  ("2b08", "Relative Runtime In A Generic Level Range", "GATT Characteristic and Object Type"),
  ("2b09", "Relative Value In A Voltage Range", "GATT Characteristic and Object Type"),
  ("2b0a", "Relative Value In An Illuminance Range", "GATT Characteristic and Object Type"),
  ("2b0b", "Relative Value In A Period Of Day", "GATT Characteristic and Object Type"),
  ("2b0c", "Relative Value In A Temperature Range", "GATT Characteristic and Object Type"),
  ("2b0d", "Temperature 8", "GATT Characteristic and Object Type"),
  ("2b0e", "Temperature 8 In A Period Of Day", "GATT Characteristic and Object Type"),
  ("2b0f", "Temperature 8 Statistics", "GATT Characteristic and Object Type"),
  ("2b10", "Temperature Range", "GATT Characteristic and Object Type"),
  ("2b11", "Temperature Statistics", "GATT Characteristic and Object Type"),
  ("2b12", "Time Decihour 8", "GATT Characteristic and Object Type"),
  ("2b13", "Time Exponential 8", "GATT Characteristic and Object Type"),
  ("2b14", "Time Hour 24", "GATT Characteristic and Object Type"),
  ("2b15", "Time Millisecond 24", "GATT Characteristic and Object Type"),
  ("2b16", "Time Second 16", "GATT Characteristic and Object Type"),
  ("2b17", "Time Second 8", "GATT Characteristic and Object Type"),
  ("2b18", "Voltage", "GATT Characteristic and Object Type"),
  ("2b19", "Voltage Specification", "GATT Characteristic and Object Type"),
  ("2b1a", "Voltage Statistics", "GATT Characteristic and Object Type"),
  ("2b1b", "Volume Flow", "GATT Characteristic and Object Type"),
  ("2b1c", "Chromaticity Coordinate", "GATT Characteristic and Object Type"),
  ("2b1d", "RC Feature", "GATT Characteristic and Object Type"),
  ("2b1e", "RC Settings", "GATT Characteristic and Object Type"),
  ("2b1f", "Reconnection Configuration Control Point", "GATT Characteristic and Object Type"),
  ("2b20", "IDD Status Changed", "GATT Characteristic and Object Type"),
  ("2b21", "IDD Status", "GATT Characteristic and Object Type"),
  ("2b22", "IDD Annunciation Status", "GATT Characteristic and Object Type"),
  ("2b23", "IDD Features", "GATT Characteristic and Object Type"),
  ("2b24", "IDD Status Reader Control Point", "GATT Characteristic and Object Type"),
  ("2b25", "IDD Command Control Point", "GATT Characteristic and Object Type"),
  ("2b26", "IDD Command Data", "GATT Characteristic and Object Type"),
  ("2b27", "IDD Record Access Control Point", "GATT Characteristic and Object Type"),
  ("2b28", "IDD History Data", "GATT Characteristic and Object Type"),
  ("2b29", "Client Supported Features", "GATT Characteristic and Object Type"),
  ("2b2a", "Database Hash", "GATT Characteristic and Object Type"),
  ("2b2b", "BSS Control Point", "GATT Characteristic and Object Type"),
  ("2b2c", "BSS Response", "GATT Characteristic and Object Type"),
  ("2b2d", "Emergency ID", "GATT Characteristic and Object Type"),
  ("2b2e", "Emergency Text", "GATT Characteristic and Object Type"),
  ("2b34", "Enhanced Blood Pressure Measurement", "GATT Characteristic and Object Type"),
  ("2b35", "Enhanced Intermediate Cuff Pressure", "GATT Characteristic and Object Type"),
  ("2b36", "Blood Pressure Record", "GATT Characteristic and Object Type"),
  ("2b38", "BR-EDR Handover Data", "GATT Characteristic and Object Type"),
  ("2b39", "Bluetooth SIG Data", "GATT Characteristic and Object Type"),
  ("2b3a", "Server Supported Features", "GATT Characteristic and Object Type"),
  ("2b3b", "Physical Activity Monitor Features", "GATT Characteristic and Object Type"),
  ("2b3c", "General Activity Instantaneous Data", "GATT Characteristic and Object Type"),
  ("2b3d", "General Activity Summary Data", "GATT Characteristic and Object Type"),
  ("2b3e", "CardioRespiratory Activity Instantaneous Data", "GATT Characteristic and Object Type"),
  ("2b3f", "CardioRespiratory Activity Summary Data", "GATT Characteristic and Object Type"),
  ("2b40", "Step Counter Activity Summary Data", "GATT Characteristic and Object Type"),
  ("2b41", "Sleep Activity Instantaneous Data", "GATT Characteristic and Object Type"),
  ("2b42", "Sleep Activity Summary Data", "GATT Characteristic and Object Type"),
  ("2b43", "Physical Activity Monitor Control Point", "GATT Characteristic and Object Type"),
  ("2b44", "Current Session", "GATT Characteristic and Object Type"),
  ("2b45", "Session", "GATT Characteristic and Object Type"),
  ("2b46", "Preferred Units", "GATT Characteristic and Object Type"),
  ("2b47", "High Resolution Height", "GATT Characteristic and Object Type"),
  ("2b48", "Middle Name", "GATT Characteristic and Object Type"),
  ("2b49", "Stride Length", "GATT Characteristic and Object Type"),
  ("2b4a", "Handedness", "GATT Characteristic and Object Type"),
  ("2b4b", "Device Wearing Position", "GATT Characteristic and Object Type"),
  ("2b4c", "Four Zone Heart Rate Limits", "GATT Characteristic and Object Type"),
  ("2b4d", "High Intensity Exercise Threshold", "GATT Characteristic and Object Type"),
  ("2b4e", "Activity Goal", "GATT Characteristic and Object Type"),
  ("2b4f", "Sedentary Interval Notification", "GATT Characteristic and Object Type"),
  ("2b50", "Caloric Intake", "GATT Characteristic and Object Type"),
  ("2b77", "Audio Input State", "GATT Characteristic and Object Type"),
  ("2b78", "Gain Settings Attribute", "GATT Characteristic and Object Type"),
  ("2b79", "Audio Input Type", "GATT Characteristic and Object Type"),
  ("2b7a", "Audio Input Status", "GATT Characteristic and Object Type"),
  ("2b7b", "Audio Input Control Point", "GATT Characteristic and Object Type"),
  ("2b7c", "Audio Input Description", "GATT Characteristic and Object Type"),
  ("2b7d", "Volume State", "GATT Characteristic and Object Type"),
  ("2b7e", "Volume Control Point", "GATT Characteristic and Object Type"),
  ("2b7f", "Volume Flags", "GATT Characteristic and Object Type"),
  ("2b80", "Offset State", "GATT Characteristic and Object Type"),
  ("2b81", "Audio Location", "GATT Characteristic and Object Type"),
  ("2b82", "Volume Offset Control Point", "GATT Characteristic and Object Type"),
  ("2b83", "Audio Output Description", "GATT Characteristic and Object Type"),
  ("2b84", "Set Identity Resolving Key Characteristic", "GATT Characteristic and Object Type"),
  ("2b85", "Size Characteristic", "GATT Characteristic and Object Type"),
  ("2b86", "Lock Characteristic", "GATT Characteristic and Object Type"),
  ("2b87", "Rank Characteristic", "GATT Characteristic and Object Type"),
  ("2b8e", "Device Time Feature", "GATT Characteristic and Object Type"),
  ("2b8f", "Device Time Parameters", "GATT Characteristic and Object Type"),
  ("2b90", "Device Time", "GATT Characteristic and Object Type"),
  ("2b91", "Device Time Control Point", "GATT Characteristic and Object Type"),
  ("2b92", "Time Change Log Data", "GATT Characteristic and Object Type"),
  ("2b93", "Media Player Name", "GATT Characteristic and Object Type"),
  ("2b94", "Media Player Icon Object ID", "GATT Characteristic and Object Type"),
  ("2b95", "Media Player Icon URL", "GATT Characteristic and Object Type"),
  ("2b96", "Track Changed", "GATT Characteristic and Object Type"),
  ("2b97", "Track Title", "GATT Characteristic and Object Type"),
  ("2b98", "Track Duration", "GATT Characteristic and Object Type"),
  ("2b99", "Track Position", "GATT Characteristic and Object Type"),
  ("2b9a", "Playback Speed", "GATT Characteristic and Object Type"),
  ("2b9b", "Seeking Speed", "GATT Characteristic and Object Type"),
  ("2b9c", "Current Track Segments Object ID", "GATT Characteristic and Object Type"),
  ("2b9d", "Current Track Object ID", "GATT Characteristic and Object Type"),
  ("2b9e", "Next Track Object ID", "GATT Characteristic and Object Type"),
  ("2b9f", "Parent Group Object ID", "GATT Characteristic and Object Type"),
  ("2ba0", "Current Group Object ID", "GATT Characteristic and Object Type"),
  ("2ba1", "Playing Order", "GATT Characteristic and Object Type"),
  ("2ba2", "Playing Orders Supported", "GATT Characteristic and Object Type"),
  ("2ba3", "Media State", "GATT Characteristic and Object Type"),
  ("2ba4", "Media Control Point", "GATT Characteristic and Object Type"),
  ("2ba5", "Media Control Point Opcodes Supported", "GATT Characteristic and Object Type"),
  ("2ba6", "Search Results Object ID", "GATT Characteristic and Object Type"),
  ("2ba7", "Search Control Point", "GATT Characteristic and Object Type"),
  ("2ba9", "Media Player Icon Object Type", "GATT Characteristic and Object Type"),
  ("2baa", "Track Segments Object Type", "GATT Characteristic and Object Type"),
  ("2bab", "Track Object Type", "GATT Characteristic and Object Type"),
  ("2bac", "Group Object Type", "GATT Characteristic and Object Type"),
  ("2bad", "Constant Tone Extension Enable", "GATT Characteristic and Object Type"),
  ("2bae", "Advertising Constant Tone Extension Minimum Length", "GATT Characteristic and Object Type"),
  ("2baf", "Advertising Constant Tone Extension Minimum Transmit Count", "GATT Characteristic and Object Type"),
  ("2bb0", "Advertising Constant Tone Extension Transmit Duration", "GATT Characteristic and Object Type"),
  ("2bb1", "Advertising Constant Tone Extension Interval", "GATT Characteristic and Object Type"),
  ("2bb2", "Advertising Constant Tone Extension PHY", "GATT Characteristic and Object Type"),
  ("2bb3", "Bearer Provider Name", "GATT Characteristic and Object Type"),
  ("2bb4", "Bearer UCI", "GATT Characteristic and Object Type"),
  ("2bb5", "Bearer Technology", "GATT Characteristic and Object Type"),
  ("2bb6", "Bearer URI Schemes Supported List", "GATT Characteristic and Object Type"),
  ("2bb7", "Bearer Signal Strength", "GATT Characteristic and Object Type"),
  ("2bb8", "Bearer Signal Strength Reporting Interval", "GATT Characteristic and Object Type"),
  ("2bb9", "Bearer List Current Calls", "GATT Characteristic and Object Type"),
  ("2bba", "Content Control ID", "GATT Characteristic and Object Type"),
  ("2bbb", "Status Flags", "GATT Characteristic and Object Type"),
  ("2bbc", "Incoming Call Target Bearer URI", "GATT Characteristic and Object Type"),
  ("2bbd", "Call State", "GATT Characteristic and Object Type"),
  ("2bbe", "Call Control Point", "GATT Characteristic and Object Type"),
  ("2bbf", "Call Control Point Optional Opcodes", "GATT Characteristic and Object Type"),
  ("2bc0", "Termination Reason", "GATT Characteristic and Object Type"),
  ("2bc1", "Incoming Call", "GATT Characteristic and Object Type"),
  ("2bc2", "Call Friendly Name", "GATT Characteristic and Object Type"),
  ("2bc3", "Mute", "GATT Characteristic and Object Type"),
  ("fd15", "Setup Assist Service for Home Equipments", "16-bit UUID for members"),
  ("fd16", "Sensitech, Inc.", "16-bit UUID for members"),
  ("fd17", "LEGIC Identsystems AG", "16-bit UUID for members"),
  ("fd18", "LEGIC Identsystems AG", "16-bit UUID for members"),
  ("fd19", "Smith & Nephew Medical Limited", "16-bit UUID for members"),
  ("fd1a", "CSIRO", "16-bit UUID for members"),
  ("fd1b", "Helios Sports, Inc.", "16-bit UUID for members"),
  ("fd1c", "Brady Worldwide Inc.", "16-bit UUID for members"),
  ("fd1d", "Samsung Electronics Co., Ltd", "16-bit UUID for members"),
  ("fd1e", "Plume Design Inc.", "16-bit UUID for members"),
  ("fd1f", "3M", "16-bit UUID for members"),
  ("fd20", "GN Hearing A/S", "16-bit UUID for members"),
  ("fd21", "Huawei Technologies Co., Ltd.", "16-bit UUID for members"),
  ("fd22", "Huawei Technologies Co., Ltd.", "16-bit UUID for members"),
  ("fd23", "DOM Sicherheitstechnik GmbH & Co. KG", "16-bit UUID for members"),
  ("fd24", "GD Midea Air-Conditioning Equipment Co., Ltd.", "16-bit UUID for members"),
  ("fd25", "GD Midea Air-Conditioning Equipment Co., Ltd.", "16-bit UUID for members"),
  ("fd26", "Novo Nordisk A/S", "16-bit UUID for members"),
  ("fd27", "i2Systems", "16-bit UUID for members"),
  ("fd28", "Julius Blum GmbH", "16-bit UUID for members"),
  ("fd29", "Asahi Kasei Corporation", "16-bit UUID for members"),
  ("fd2a", "Sony Corporation", "16-bit UUID for members"),
  ("fd2b", "The Access Technologies", "16-bit UUID for members"),
  ("fd2c", "The Access Technologies", "16-bit UUID for members"),
  ("fd2d", "Xiaomi Inc.", "16-bit UUID for members"),
  ("fd2e", "Bitstrata Systems Inc.", "16-bit UUID for members"),
  ("fd2f", "Bitstrata Systems Inc.", "16-bit UUID for members"),
  ("fd30", "Sesam Solutions BV", "16-bit UUID for members"),
  ("fd31", "LG Electronics Inc.", "16-bit UUID for members"),
  ("fd32", "Gemalto Holding BV", "16-bit UUID for members"),
  ("fd33", "DashLogic, Inc.", "16-bit UUID for members"),
  ("fd34", "Aerosens LLC.", "16-bit UUID for members"),
  ("fd35", "Transsion Holdings Limited", "16-bit UUID for members"),
  ("fd36", "Google LLC", "16-bit UUID for members"),
  ("fd37", "TireCheck GmbH", "16-bit UUID for members"),
  ("fd38", "Danfoss A/S", "16-bit UUID for members"),
  ("fd39", "PREDIKTAS", "16-bit UUID for members"),
  ("fd3a", "Verkada Inc.", "16-bit UUID for members"),
  ("fd3b", "Verkada Inc.", "16-bit UUID for members"),
  ("fd3c", "Redline Communications Inc.", "16-bit UUID for members"),
  ("fd3d", "Woan Technology (Shenzhen) Co., Ltd.", "16-bit UUID for members"),
  ("fd3e", "Pure Watercraft, inc.", "16-bit UUID for members"),
  ("fd3f", "Cognosos, Inc", "16-bit UUID for members"),
  ("fd40", "Beflex Inc.", "16-bit UUID for members"),
  ("fd41", "Amazon Lab126", "16-bit UUID for members"),
  ("fd42", "Globe (Jiangsu) Co.,Ltd", "16-bit UUID for members"),
  ("fd43", "Apple Inc.", "16-bit UUID for members"),
  ("fd44", "Apple Inc.", "16-bit UUID for members"),
  ("fd45", "GB Solution co.,Ltd", "16-bit UUID for members"),
  ("fd46", "Lemco IKE", "16-bit UUID for members"),
  ("fd47", "Liberty Global Inc.", "16-bit UUID for members"),
  ("fd48", "Geberit International AG", "16-bit UUID for members"),
  ("fd49", "Panasonic Corporation", "16-bit UUID for members"),
  ("fd4a", "Sigma Elektro GmbH", "16-bit UUID for members"),
  ("fd4b", "Samsung Electronics Co., Ltd.", "16-bit UUID for members"),
  ("fd4c", "Adolf Wuerth GmbH & Co KG", "16-bit UUID for members"),
  ("fd4d", "70mai Co.,Ltd.", "16-bit UUID for members"),
  ("fd4e", "70mai Co.,Ltd.", "16-bit UUID for members"),
  ("fd4f", "Forkbeard Technologies AS", "16-bit UUID for members"),
  ("fd50", "Hangzhou Tuya Information Technology Co., Ltd", "16-bit UUID for members"),
  ("fd51", "UTC Fire and Security", "16-bit UUID for members"),
  ("fd52", "UTC Fire and Security", "16-bit UUID for members"),
  ("fd53", "PCI Private Limited", "16-bit UUID for members"),
  ("fd54", "Qingdao Haier Technology Co., Ltd.", "16-bit UUID for members"),
  ("fd55", "Braveheart Wireless, Inc.", "16-bit UUID for members"),
  ("fd56", "Resmed Ltd", "16-bit UUID for members"),
  ("fd57", "Volvo Car Corporation", "16-bit UUID for members"),
  ("fd58", "Volvo Car Corporation", "16-bit UUID for members"),
  ("fd59", "Samsung Electronics Co., Ltd.", "16-bit UUID for members"),
  ("fd5a", "Samsung Electronics Co., Ltd.", "16-bit UUID for members"),
  ("fd5b", "V2SOFT INC.", "16-bit UUID for members"),
  ("fd5c", "React Mobile", "16-bit UUID for members"),
  ("fd5d", "maxon motor ltd.", "16-bit UUID for members"),
  ("fd5e", "Tapkey GmbH", "16-bit UUID for members"),
  ("fd5f", "Oculus VR, LLC", "16-bit UUID for members"),
  ("fd60", "Sercomm Corporation", "16-bit UUID for members"),
  ("fd61", "Arendi AG", "16-bit UUID for members"),
  ("fd62", "Fitbit, Inc.", "16-bit UUID for members"),
  ("fd63", "Fitbit, Inc.", "16-bit UUID for members"),
  ("fd64", "INRIA", "16-bit UUID for members"),
  ("fd65", "Razer Inc.", "16-bit UUID for members"),
  ("fd66", "Zebra Technologies Corporation", "16-bit UUID for members"),
  ("fd67", "Montblanc Simplo GmbH", "16-bit UUID for members"),
  ("fd68", "Ubique Innovation AG", "16-bit UUID for members"),
  ("fd69", "Samsung Electronics Co., Ltd", "16-bit UUID for members"),
  ("fd6a", "Emerson", "16-bit UUID for members"),
  ("fd6b", "rapitag GmbH", "16-bit UUID for members"),
  ("fd6c", "Samsung Electronics Co., Ltd.", "16-bit UUID for members"),
  ("fd6d", "Sigma Elektro GmbH", "16-bit UUID for members"),
  ("fd6e", "Polidea sp. z o.o.", "16-bit UUID for members"),
  ("fd6f", "Apple, Inc.", "16-bit UUID for members"),
  ("fd70", "GuangDong Oppo Mobile Telecommunications Corp., Ltd", "16-bit UUID for members"),
  ("fd71", "GN Hearing A/S", "16-bit UUID for members"),
  ("fd72", "Logitech International SA", "16-bit UUID for members"),
  ("fd73", "BRControls Products BV", "16-bit UUID for members"),
  ("fd74", "BRControls Products BV", "16-bit UUID for members"),
  ("fd75", "Insulet Corporation", "16-bit UUID for members"),
  ("fd76", "Insulet Corporation", "16-bit UUID for members"),
  ("fd77", "Withings", "16-bit UUID for members"),
  ("fd78", "Withings", "16-bit UUID for members"),
  ("fd79", "Withings", "16-bit UUID for members"),
  ("fd7a", "Withings", "16-bit UUID for members"),
  ("fd7b", "WYZE LABS, INC.", "16-bit UUID for members"),
  ("fd7c", "Toshiba Information Systems(Japan) Corporation", "16-bit UUID for members"),
  ("fd7d", "Center for Advanced Research Wernher Von Braun", "16-bit UUID for members"),
  ("fd7e", "Samsung Electronics Co., Ltd.", "16-bit UUID for members"),
  ("fd7f", "Husqvarna AB", "16-bit UUID for members"),
  ("fd80", "Phindex Technologies, Inc", "16-bit UUID for members"),
  ("fd81", "CANDY HOUSE, Inc.", "16-bit UUID for members"),
  ("fd82", "Sony Corporation", "16-bit UUID for members"),
  ("fd83", "iNFORM Technology GmbH", "16-bit UUID for members"),
  ("fd84", "Tile, Inc.", "16-bit UUID for members"),
  ("fd85", "Husqvarna AB", "16-bit UUID for members"),
  ("fd86", "Abbott", "16-bit UUID for members"),
  ("fd87", "Google LLC", "16-bit UUID for members"),
  ("fd88", "Urbanminded LTD", "16-bit UUID for members"),
  ("fd89", "Urbanminded LTD", "16-bit UUID for members"),
  ("fd8a", "Signify Netherlands B.V.", "16-bit UUID for members"),
  ("fd8b", "Jigowatts Inc.", "16-bit UUID for members"),
  ("fd8c", "Google LLC", "16-bit UUID for members"),
  ("fd8d", "quip NYC Inc.", "16-bit UUID for members"),
  ("fd8e", "Motorola Solutions", "16-bit UUID for members"),
  ("fd8f", "Matrix ComSec Pvt. Ltd.", "16-bit UUID for members"),
  ("fd90", "Guangzhou SuperSound Information Technology Co.,Ltd", "16-bit UUID for members"),
  ("fd91", "Groove X, Inc.", "16-bit UUID for members"),
  ("fd92", "Qualcomm Technologies International, Ltd. (QTIL)", "16-bit UUID for members"),
  ("fd93", "Bayerische Motoren Werke AG", "16-bit UUID for members"),
  ("fd94", "Hewlett Packard Enterprise", "16-bit UUID for members"),
  ("fd95", "Rigado", "16-bit UUID for members"),
  ("fd96", "Google LLC", "16-bit UUID for members"),
  ("fd97", "June Life, Inc.", "16-bit UUID for members"),
  ("fd98", "Disney Worldwide Services, Inc.", "16-bit UUID for members"),
  ("fd99", "ABB Oy", "16-bit UUID for members"),
  ("fd9a", "Huawei Technologies Co., Ltd.", "16-bit UUID for members"),
  ("fd9b", "Huawei Technologies Co., Ltd.", "16-bit UUID for members"),
  ("fd9c", "Huawei Technologies Co., Ltd.", "16-bit UUID for members"),
  ("fd9d", "Gastec Corporation", "16-bit UUID for members"),
  ("fd9e", "The Coca-Cola Company", "16-bit UUID for members"),
  ("fd9f", "VitalTech Affiliates LLC", "16-bit UUID for members"),
  ("fda0", "Secugen Corporation", "16-bit UUID for members"),
  ("fda1", "Groove X, Inc", "16-bit UUID for members"),
  ("fda2", "Groove X, Inc", "16-bit UUID for members"),
  ("fda3", "Inseego Corp.", "16-bit UUID for members"),
  ("fda4", "Inseego Corp.", "16-bit UUID for members"),
  ("fda5", "Neurostim OAB, Inc.", "16-bit UUID for members"),
  ("fda6", "WWZN Information Technology Company Limited", "16-bit UUID for members"),
  ("fda7", "WWZN Information Technology Company Limited", "16-bit UUID for members"),
  ("fda8", "PSA Peugeot Citro n", "16-bit UUID for members"),
  ("fda9", "Rhombus Systems, Inc.", "16-bit UUID for members"),
  ("fdaa", "Xiaomi Inc.", "16-bit UUID for members"),
  ("fdab", "Xiaomi Inc.", "16-bit UUID for members"),
  ("fdac", "Tentacle Sync GmbH", "16-bit UUID for members"),
  ("fdad", "Houwa System Design, k.k.", "16-bit UUID for members"),
  ("fdae", "Houwa System Design, k.k.", "16-bit UUID for members"),
  ("fdaf", "Wiliot LTD", "16-bit UUID for members"),
  ("fdb0", "Proxy Technologies, Inc.", "16-bit UUID for members"),
  ("fdb1", "Proxy Technologies, Inc.", "16-bit UUID for members"),
  ("fdb2", "Portable Multimedia Ltd", "16-bit UUID for members"),
  ("fdb3", "Audiodo AB", "16-bit UUID for members"),
  ("fdb4", "HP Inc", "16-bit UUID for members"),
  ("fdb5", "ECSG", "16-bit UUID for members"),
  ("fdb6", "GWA Hygiene GmbH", "16-bit UUID for members"),
  ("fdb7", "LivaNova USA Inc.", "16-bit UUID for members"),
  ("fdb8", "LivaNova USA Inc.", "16-bit UUID for members"),
  ("fdb9", "Comcast Cable Corporation", "16-bit UUID for members"),
  ("fdba", "Comcast Cable Corporation", "16-bit UUID for members"),
  ("fdbb", "Profoto", "16-bit UUID for members"),
  ("fdbc", "Emerson", "16-bit UUID for members"),
  ("fdbd", "Clover Network, Inc.", "16-bit UUID for members"),
  ("fdbe", "California Things Inc.", "16-bit UUID for members"),
  ("fdbf", "California Things Inc.", "16-bit UUID for members"),
  ("fdc0", "Hunter Douglas", "16-bit UUID for members"),
  ("fdc1", "Hunter Douglas", "16-bit UUID for members"),
  ("fdc2", "Baidu Online Network Technology (Beijing) Co., Ltd", "16-bit UUID for members"),
  ("fdc3", "Baidu Online Network Technology (Beijing) Co., Ltd", "16-bit UUID for members"),
  ("fdc4", "Simavita (Aust) Pty Ltd", "16-bit UUID for members"),
  ("fdc5", "Automatic Labs", "16-bit UUID for members"),
  ("fdc6", "Eli Lilly and Company", "16-bit UUID for members"),
  ("fdc7", "Eli Lilly and Company", "16-bit UUID for members"),
  ("fdc8", "Hach – Danaher", "16-bit UUID for members"),
  ("fdc9", "Busch-Jaeger Elektro GmbH", "16-bit UUID for members"),
  ("fdca", "Fortin Electronic Systems", "16-bit UUID for members"),
  ("fdcb", "Meggitt SA", "16-bit UUID for members"),
  ("fdcc", "Shoof Technologies", "16-bit UUID for members"),
  ("fdcd", "Qingping Technology (Beijing) Co., Ltd.", "16-bit UUID for members"),
  ("fdce", "SENNHEISER electronic GmbH & Co. KG", "16-bit UUID for members"),
  ("fdcf", "Nalu Medical, Inc", "16-bit UUID for members"),
  ("fdd0", "Huawei Technologies Co., Ltd", "16-bit UUID for members"),
  ("fdd1", "Huawei Technologies Co., Ltd", "16-bit UUID for members"),
  ("fdd2", "Bose Corporation", "16-bit UUID for members"),
  ("fdd3", "FUBA Automotive Electronics GmbH", "16-bit UUID for members"),
  ("fdd4", "LX Solutions Pty Limited", "16-bit UUID for members"),
  ("fdd5", "Brompton Bicycle Ltd", "16-bit UUID for members"),
  ("fdd6", "Ministry of Supply", "16-bit UUID for members"),
  ("fdd7", "Emerson", "16-bit UUID for members"),
  ("fdd8", "Jiangsu Teranovo Tech Co., Ltd.", "16-bit UUID for members"),
  ("fdd9", "Jiangsu Teranovo Tech Co., Ltd.", "16-bit UUID for members"),
  ("fdda", "MHCS", "16-bit UUID for members"),
  ("fddb", "Samsung Electronics Co., Ltd.", "16-bit UUID for members"),
  ("fddc", "4iiii Innovations Inc.", "16-bit UUID for members"),
  ("fddd", "Arch Systems Inc", "16-bit UUID for members"),
  ("fdde", "Noodle Technology Inc.", "16-bit UUID for members"),
  ("fddf", "Harman International", "16-bit UUID for members"),
  ("fde0", "John Deere", "16-bit UUID for members"),
  ("fde1", "Fortin Electronic Systems", "16-bit UUID for members"),
  ("fde2", "Google Inc.", "16-bit UUID for members"),
  ("fde3", "Abbott Diabetes Care", "16-bit UUID for members"),
  ("fde4", "JUUL Labs, Inc.", "16-bit UUID for members"),
  ("fde5", "SMK Corporation", "16-bit UUID for members"),
  ("fde6", "Intelletto Technologies Inc", "16-bit UUID for members"),
  ("fde7", "SECOM Co., LTD", "16-bit UUID for members"),
  ("fde8", "Robert Bosch GmbH", "16-bit UUID for members"),
  ("fde9", "Spacesaver Corporation", "16-bit UUID for members"),
  ("fdea", "SeeScan, Inc", "16-bit UUID for members"),
  ("fdeb", "Syntronix Corporation", "16-bit UUID for members"),
  ("fdec", "Mannkind Corporation", "16-bit UUID for members"),
  ("fded", "Pole Star", "16-bit UUID for members"),
  ("fdee", "Huawei Technologies Co., Ltd.", "16-bit UUID for members"),
  ("fdef", "ART AND PROGRAM, INC.", "16-bit UUID for members"),
  ("fdf0", "Google Inc.", "16-bit UUID for members"),
  ("fdf1", "LAMPLIGHT Co.,Ltd", "16-bit UUID for members"),
  ("fdf2", "AMICCOM Electronics Corporation", "16-bit UUID for members"),
  ("fdf3", "Amersports", "16-bit UUID for members"),
  ("fdf4", "O. E. M. Controls, Inc.", "16-bit UUID for members"),
  ("fdf5", "Milwaukee Electric Tools", "16-bit UUID for members"),
  ("fdf6", "AIAIAI ApS", "16-bit UUID for members"),
  ("fdf7", "HP Inc.", "16-bit UUID for members"),
  ("fdf8", "Onvocal", "16-bit UUID for members"),
  ("fdf9", "INIA", "16-bit UUID for members"),
  ("fdfa", "Tandem Diabetes Care", "16-bit UUID for members"),
  ("fdfb", "Tandem Diabetes Care", "16-bit UUID for members"),
  ("fdfc", "Optrel AG", "16-bit UUID for members"),
  ("fdfd", "RecursiveSoft Inc.", "16-bit UUID for members"),
  ("fdfe", "ADHERIUM(NZ) LIMITED", "16-bit UUID for members"),
  ("fdff", "OSRAM GmbH", "16-bit UUID for members"),
  ("fe00", "Amazon.com Services, Inc.", "16-bit UUID for members"),
  ("fe01", "Duracell U.S. Operations Inc.", "16-bit UUID for members"),
  ("fe02", "Robert Bosch GmbH", "16-bit UUID for members"),
  ("fe03", "Amazon.com Services, Inc.", "16-bit UUID for members"),
  ("fe04", "OpenPath Security Inc", "16-bit UUID for members"),
  ("fe05", "CORE Transport Technologies NZ Limited", "16-bit UUID for members"),
  ("fe06", "Qualcomm Technologies, Inc.", "16-bit UUID for members"),
  ("fe07", "Sonos, Inc.", "16-bit UUID for members"),
  ("fe08", "Microsoft", "16-bit UUID for members"),
  ("fe09", "Pillsy, Inc.", "16-bit UUID for members"),
  ("fe0a", "ruwido austria gmbh", "16-bit UUID for members"),
  ("fe0b", "ruwido austria gmbh", "16-bit UUID for members"),
  ("fe0c", "Procter & Gamble", "16-bit UUID for members"),
  ("fe0d", "Procter & Gamble", "16-bit UUID for members"),
  ("fe0e", "Setec Pty Ltd", "16-bit UUID for members"),
  ("fe0f", "Signify Netherlands B.V. (formerly Philips Lighting B.V.)", "16-bit UUID for members"),
  ("fe10", "LAPIS Technology Co., Ltd.", "16-bit UUID for members"),
  ("fe11", "GMC-I Messtechnik GmbH", "16-bit UUID for members"),
  ("fe12", "M-Way Solutions GmbH", "16-bit UUID for members"),
  ("fe13", "Apple Inc.", "16-bit UUID for members"),
  ("fe14", "Flextronics International USA Inc.", "16-bit UUID for members"),
  ("fe15", "Amazon.com Services, Inc..", "16-bit UUID for members"),
  ("fe16", "Footmarks, Inc.", "16-bit UUID for members"),
  ("fe17", "Telit Wireless Solutions GmbH", "16-bit UUID for members"),
  ("fe18", "Runtime, Inc.", "16-bit UUID for members"),
  ("fe19", "Google, Inc", "16-bit UUID for members"),
  ("fe1a", "Tyto Life LLC", "16-bit UUID for members"),
  ("fe1b", "Tyto Life LLC", "16-bit UUID for members"),
  ("fe1c", "NetMedia, Inc.", "16-bit UUID for members"),
  ("fe1d", "Illuminati Instrument Corporation", "16-bit UUID for members"),
  ("fe1e", "Smart Innovations Co., Ltd", "16-bit UUID for members"),
  ("fe1f", "Garmin International, Inc.", "16-bit UUID for members"),
  ("fe20", "Emerson", "16-bit UUID for members"),
  ("fe21", "Bose Corporation", "16-bit UUID for members"),
  ("fe22", "Zoll Medical Corporation", "16-bit UUID for members"),
  ("fe23", "Zoll Medical Corporation", "16-bit UUID for members"),
  ("fe24", "August Home Inc", "16-bit UUID for members"),
  ("fe25", "Apple, Inc.", "16-bit UUID for members"),
  ("fe26", "Google", "16-bit UUID for members"),
  ("fe27", "Google", "16-bit UUID for members"),
  ("fe28", "Ayla Networks", "16-bit UUID for members"),
  ("fe29", "Gibson Innovations", "16-bit UUID for members"),
  ("fe2a", "DaisyWorks, Inc.", "16-bit UUID for members"),
  ("fe2b", "ITT Industries", "16-bit UUID for members"),
  ("fe2c", "Google", "16-bit UUID for members"),
  ("fe2d", "SMART INNOVATION Co.,Ltd", "16-bit UUID for members"),
  ("fe2e", "ERi,Inc.", "16-bit UUID for members"),
  ("fe2f", "CRESCO Wireless, Inc", "16-bit UUID for members"),
  ("fe30", "Volkswagen AG", "16-bit UUID for members"),
  ("fe31", "Volkswagen AG", "16-bit UUID for members"),
  ("fe32", "Pro-Mark, Inc.", "16-bit UUID for members"),
  ("fe33", "CHIPOLO d.o.o.", "16-bit UUID for members"),
  ("fe34", "SmallLoop LLC", "16-bit UUID for members"),
  ("fe35", "HUAWEI Technologies Co., Ltd", "16-bit UUID for members"),
  ("fe36", "HUAWEI Technologies Co., Ltd", "16-bit UUID for members"),
  ("fe37", "Spaceek LTD", "16-bit UUID for members"),
  ("fe38", "Spaceek LTD", "16-bit UUID for members"),
  ("fe39", "TTS Tooltechnic Systems AG & Co. KG", "16-bit UUID for members"),
  ("fe3a", "TTS Tooltechnic Systems AG & Co. KG", "16-bit UUID for members"),
  ("fe3b", "Dolby Laboratories", "16-bit UUID for members"),
  ("fe3c", "alibaba", "16-bit UUID for members"),
  ("fe3d", "BD Medical", "16-bit UUID for members"),
  ("fe3e", "BD Medical", "16-bit UUID for members"),
  ("fe3f", "Friday Labs Limited", "16-bit UUID for members"),
  ("fe40", "Inugo Systems Limited", "16-bit UUID for members"),
  ("fe41", "Inugo Systems Limited", "16-bit UUID for members"),
  ("fe42", "Nets A/S", "16-bit UUID for members"),
  ("fe43", "Andreas Stihl AG & Co. KG", "16-bit UUID for members"),
  ("fe44", "SK Telecom", "16-bit UUID for members"),
  ("fe45", "Snapchat Inc", "16-bit UUID for members"),
  ("fe46", "B&O Play A/S", "16-bit UUID for members"),
  ("fe47", "General Motors", "16-bit UUID for members"),
  ("fe48", "General Motors", "16-bit UUID for members"),
  ("fe49", "SenionLab AB", "16-bit UUID for members"),
  ("fe4a", "OMRON HEALTHCARE Co., Ltd.", "16-bit UUID for members"),
  ("fe4b", "Signify Netherlands B.V. (formerly Philips Lighting B.V.)", "16-bit UUID for members"),
  ("fe4c", "Volkswagen AG", "16-bit UUID for members"),
  ("fe4d", "Casambi Technologies Oy", "16-bit UUID for members"),
  ("fe4e", "NTT docomo", "16-bit UUID for members"),
  ("fe4f", "Molekule, Inc.", "16-bit UUID for members"),
  ("fe50", "Google Inc.", "16-bit UUID for members"),
  ("fe51", "SRAM", "16-bit UUID for members"),
  ("fe52", "SetPoint Medical", "16-bit UUID for members"),
  ("fe53", "3M", "16-bit UUID for members"),
  ("fe54", "Motiv, Inc.", "16-bit UUID for members"),
  ("fe55", "Google Inc.", "16-bit UUID for members"),
  ("fe56", "Google Inc.", "16-bit UUID for members"),
  ("fe57", "Dotted Labs", "16-bit UUID for members"),
  ("fe58", "Nordic Semiconductor ASA", "16-bit UUID for members"),
  ("fe59", "Nordic Semiconductor ASA", "16-bit UUID for members"),
  ("fe5a", "Cronologics Corporation", "16-bit UUID for members"),
  ("fe5b", "GT-tronics HK Ltd", "16-bit UUID for members"),
  ("fe5c", "million hunters GmbH", "16-bit UUID for members"),
  ("fe5d", "Grundfos A/S", "16-bit UUID for members"),
  ("fe5e", "Plastc Corporation", "16-bit UUID for members"),
  ("fe5f", "Eyefi, Inc.", "16-bit UUID for members"),
  ("fe60", "Lierda Science & Technology Group Co., Ltd.", "16-bit UUID for members"),
  ("fe61", "Logitech International SA", "16-bit UUID for members"),
  ("fe62", "Indagem Tech LLC", "16-bit UUID for members"),
  ("fe63", "Connected Yard, Inc.", "16-bit UUID for members"),
  ("fe64", "Siemens AG", "16-bit UUID for members"),
  ("fe65", "CHIPOLO d.o.o.", "16-bit UUID for members"),
  ("fe66", "Intel Corporation", "16-bit UUID for members"),
  ("fe67", "Lab Sensor Solutions", "16-bit UUID for members"),
  ("fe68", "Qualcomm Life Inc", "16-bit UUID for members"),
  ("fe69", "Qualcomm Life Inc", "16-bit UUID for members"),
  ("fe6a", "Kontakt Micro-Location Sp. z o.o.", "16-bit UUID for members"),
  ("fe6b", "TASER International, Inc.", "16-bit UUID for members"),
  ("fe6c", "TASER International, Inc.", "16-bit UUID for members"),
  ("fe6d", "The University of Tokyo", "16-bit UUID for members"),
  ("fe6e", "The University of Tokyo", "16-bit UUID for members"),
  ("fe6f", "LINE Corporation", "16-bit UUID for members"),
  ("fe70", "Beijing Jingdong Century Trading Co., Ltd.", "16-bit UUID for members"),
  ("fe71", "Plume Design Inc", "16-bit UUID for members"),
  ("fe72", "Abbott (formerly St. Jude Medical, Inc.)", "16-bit UUID for members"),
  ("fe73", "Abbott (formerly St. Jude Medical, Inc.)", "16-bit UUID for members"),
  ("fe74", "unwire", "16-bit UUID for members"),
  ("fe75", "TangoMe", "16-bit UUID for members"),
  ("fe76", "TangoMe", "16-bit UUID for members"),
  ("fe77", "Hewlett-Packard Company", "16-bit UUID for members"),
  ("fe78", "Hewlett-Packard Company", "16-bit UUID for members"),
  ("fe79", "Zebra Technologies", "16-bit UUID for members"),
  ("fe7a", "Bragi GmbH", "16-bit UUID for members"),
  ("fe7b", "Orion Labs, Inc.", "16-bit UUID for members"),
  ("fe7c", "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)", "16-bit UUID for members"),
  ("fe7d", "Aterica Health Inc.", "16-bit UUID for members"),
  ("fe7e", "Awear Solutions Ltd", "16-bit UUID for members"),
  ("fe7f", "Doppler Lab", "16-bit UUID for members"),
  ("fe80", "Doppler Lab", "16-bit UUID for members"),
  ("fe81", "Medtronic Inc.", "16-bit UUID for members"),
  ("fe82", "Medtronic Inc.", "16-bit UUID for members"),
  ("fe83", "Blue Bite", "16-bit UUID for members"),
  ("fe84", "RF Digital Corp", "16-bit UUID for members"),
  ("fe85", "RF Digital Corp", "16-bit UUID for members"),
  ("fe86", "HUAWEI Technologies Co., Ltd. ( 华为技术有限公司 )", "16-bit UUID for members"),
  ("fe87", "Qingdao Yeelink Information Technology Co., Ltd. ( 青岛亿联客信息技术有限公司 )", "16-bit UUID for members"),
  ("fe88", "SALTO SYSTEMS S.L.", "16-bit UUID for members"),
  ("fe89", "B&O Play A/S", "16-bit UUID for members"),
  ("fe8a", "Apple, Inc.", "16-bit UUID for members"),
  ("fe8b", "Apple, Inc.", "16-bit UUID for members"),
  ("fe8c", "TRON Forum", "16-bit UUID for members"),
  ("fe8d", "Interaxon Inc.", "16-bit UUID for members"),
  ("fe8e", "ARM Ltd", "16-bit UUID for members"),
  ("fe8f", "CSR", "16-bit UUID for members"),
  ("fe90", "JUMA", "16-bit UUID for members"),
  ("fe91", "Shanghai Imilab Technology Co.,Ltd", "16-bit UUID for members"),
  ("fe92", "Jarden Safety & Security", "16-bit UUID for members"),
  ("fe93", "OttoQ In", "16-bit UUID for members"),
  ("fe94", "OttoQ In", "16-bit UUID for members"),
  ("fe95", "Xiaomi Inc.", "16-bit UUID for members"),
  ("fe96", "Tesla Motors Inc.", "16-bit UUID for members"),
  ("fe97", "Tesla Motors Inc.", "16-bit UUID for members"),
  ("fe98", "Currant Inc", "16-bit UUID for members"),
  ("fe99", "Currant Inc", "16-bit UUID for members"),
  ("fe9a", "Estimote", "16-bit UUID for members"),
  ("fe9b", "Samsara Networks, Inc", "16-bit UUID for members"),
  ("fe9c", "GSI Laboratories, Inc.", "16-bit UUID for members"),
  ("fe9d", "Mobiquity Networks Inc", "16-bit UUID for members"),
  ("fe9e", "Dialog Semiconductor B.V.", "16-bit UUID for members"),
  ("fe9f", "Google", "16-bit UUID for members"),
  ("fea0", "Google", "16-bit UUID for members"),
  ("fea1", "Intrepid Control Systems, Inc.", "16-bit UUID for members"),
  ("fea2", "Intrepid Control Systems, Inc.", "16-bit UUID for members"),
  ("fea3", "ITT Industries", "16-bit UUID for members"),
  ("fea4", "Paxton Access Ltd", "16-bit UUID for members"),
  ("fea5", "GoPro, Inc.", "16-bit UUID for members"),
  ("fea6", "GoPro, Inc.", "16-bit UUID for members"),
  ("fea7", "UTC Fire and Security", "16-bit UUID for members"),
  ("fea8", "Savant Systems LLC", "16-bit UUID for members"),
  ("fea9", "Savant Systems LLC", "16-bit UUID for members"),
  ("feaa", "Google", "16-bit UUID for members"),
  ("feab", "Nokia", "16-bit UUID for members"),
  ("feac", "Nokia", "16-bit UUID for members"),
  ("fead", "Nokia", "16-bit UUID for members"),
  ("feae", "Nokia", "16-bit UUID for members"),
  ("feaf", "Nest Labs Inc", "16-bit UUID for members"),
  ("feb0", "Nest Labs Inc", "16-bit UUID for members"),
  ("feb1", "Electronics Tomorrow Limited", "16-bit UUID for members"),
  ("feb2", "Microsoft Corporation", "16-bit UUID for members"),
  ("feb3", "Taobao", "16-bit UUID for members"),
  ("feb4", "WiSilica Inc.", "16-bit UUID for members"),
  ("feb5", "WiSilica Inc.", "16-bit UUID for members"),
  ("feb6", "Vencer Co., Ltd", "16-bit UUID for members"),
  ("feb7", "Facebook, Inc.", "16-bit UUID for members"),
  ("feb8", "Facebook, Inc.", "16-bit UUID for members"),
  ("feb9", "LG Electronics", "16-bit UUID for members"),
  ("feba", "Tencent Holdings Limited", "16-bit UUID for members"),
  ("febb", "adafruit industries", "16-bit UUID for members"),
  ("febc", "Dexcom Inc", "16-bit UUID for members"),
  ("febd", "Clover Network, Inc", "16-bit UUID for members"),
  ("febe", "Bose Corporation", "16-bit UUID for members"),
  ("febf", "Nod, Inc.", "16-bit UUID for members"),
  ("fec0", "KDDI Corporation", "16-bit UUID for members"),
  ("fec1", "KDDI Corporation", "16-bit UUID for members"),
  ("fec2", "Blue Spark Technologies, Inc.", "16-bit UUID for members"),
  ("fec3", "360fly, Inc.", "16-bit UUID for members"),
  ("fec4", "PLUS Location Systems", "16-bit UUID for members"),
  ("fec5", "Realtek Semiconductor Corp.", "16-bit UUID for members"),
  ("fec6", "Kocomojo, LLC", "16-bit UUID for members"),
  ("fec7", "Apple, Inc.", "16-bit UUID for members"),
  ("fec8", "Apple, Inc.", "16-bit UUID for members"),
  ("fec9", "Apple, Inc.", "16-bit UUID for members"),
  ("feca", "Apple, Inc.", "16-bit UUID for members"),
  ("fecb", "Apple, Inc.", "16-bit UUID for members"),
  ("fecc", "Apple, Inc.", "16-bit UUID for members"),
  ("fecd", "Apple, Inc.", "16-bit UUID for members"),
  ("fece", "Apple, Inc.", "16-bit UUID for members"),
  ("fecf", "Apple, Inc.", "16-bit UUID for members"),
  ("fed0", "Apple, Inc.", "16-bit UUID for members"),
  ("fed1", "Apple, Inc.", "16-bit UUID for members"),
  ("fed2", "Apple, Inc.", "16-bit UUID for members"),
  ("fed3", "Apple, Inc.", "16-bit UUID for members"),
  ("fed4", "Apple, Inc.", "16-bit UUID for members"),
  ("fed5", "Plantronics Inc.", "16-bit UUID for members"),
  ("fed6", "Broadcom", "16-bit UUID for members"),
  ("fed7", "Broadcom", "16-bit UUID for members"),
  ("fed8", "Google", "16-bit UUID for members"),
  ("fed9", "Pebble Technology Corporation", "16-bit UUID for members"),
  ("feda", "ISSC Technologies Corp.", "16-bit UUID for members"),
  ("fedb", "Perka, Inc.", "16-bit UUID for members"),
  ("fedc", "Jawbone", "16-bit UUID for members"),
  ("fedd", "Jawbone", "16-bit UUID for members"),
  ("fede", "Coin, Inc.", "16-bit UUID for members"),
  ("fedf", "Design SHIFT", "16-bit UUID for members"),
  ("fee0", "Anhui Huami Information Technology Co., Ltd.", "16-bit UUID for members"),
  ("fee1", "Anhui Huami Information Technology Co., Ltd.", "16-bit UUID for members"),
  ("fee2", "Anki, Inc.", "16-bit UUID for members"),
  ("fee3", "Anki, Inc.", "16-bit UUID for members"),
  ("fee4", "Nordic Semiconductor ASA", "16-bit UUID for members"),
  ("fee5", "Nordic Semiconductor ASA", "16-bit UUID for members"),
  ("fee6", "Silvair, Inc.", "16-bit UUID for members"),
  ("fee7", "Tencent Holdings Limited.", "16-bit UUID for members"),
  ("fee8", "Quintic Corp.", "16-bit UUID for members"),
  ("fee9", "Quintic Corp.", "16-bit UUID for members"),
  ("feea", "Swirl Networks, Inc.", "16-bit UUID for members"),
  ("feeb", "Swirl Networks, Inc.", "16-bit UUID for members"),
  ("feec", "Tile, Inc.", "16-bit UUID for members"),
  ("feed", "Tile, Inc.", "16-bit UUID for members"),
  ("feee", "Polar Electro Oy", "16-bit UUID for members"),
  ("feef", "Polar Electro Oy", "16-bit UUID for members"),
  ("fef0", "Intel", "16-bit UUID for members"),
  ("fef1", "CSR", "16-bit UUID for members"),
  ("fef2", "CSR", "16-bit UUID for members"),
  ("fef3", "Google", "16-bit UUID for members"),
  ("fef4", "Google", "16-bit UUID for members"),
  ("fef5", "Dialog Semiconductor GmbH", "16-bit UUID for members"),
  ("fef6", "Wicentric, Inc.", "16-bit UUID for members"),
  ("fef7", "Aplix Corporation", "16-bit UUID for members"),
  ("fef8", "Aplix Corporation", "16-bit UUID for members"),
  ("fef9", "PayPal, Inc.", "16-bit UUID for members"),
  ("fefa", "PayPal, Inc.", "16-bit UUID for members"),
  ("fefb", "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)", "16-bit UUID for members"),
  ("fefc", "Gimbal, Inc.", "16-bit UUID for members"),
  ("fefd", "Gimbal, Inc.", "16-bit UUID for members"),
  ("fefe", "GN ReSound A/S", "16-bit UUID for members"),
  ("feff", "GN Netcom", "16-bit UUID for members"),
  ("fff3", "FiRa Consortium", "SDO GATT Service"),
  ("fff4", "FiRa Consortium", "SDO GATT Service"),
  ("fff5", "Car Connectivity Consortium, LLC", "SDO GATT Service"),
  ("fff6", "ZigBee Alliance", "SDO GATT Service"),
  ("fff7", "ZigBee Alliance", "SDO GATT Service"),
  ("fff8", "Mopria Alliance", "SDO GATT Service"),
  ("fff9", "Fast IDentity Online Alliance (FIDO)", "SDO GATT Service"),
  ("fffa", "ASTM International", "SDO GATT Service"),
  ("fffb", "Thread Group, Inc.", "SDO GATT Service"),
  ("fffc", "AirFuel Alliance", "SDO GATT Service"),
  ("fffd", "Fast IDentity Online Alliance (FIDO)", "SDO GATT Service"),
  ("fffe", "AirFuel Alliance (formerly Alliance for Wireless Power)", "SDO GATT Service");
